### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by ghost** [m5r/gatsby-transformer-blurhash#1]
Can i use it in react native?
This is very awesome and useful library

**Comment by m5r** [comment]
Hi!

This is a plugin for gatsby and can't be used as is with react native  
Although there is an official [blurhash react component](https://github.com/woltapp/react-blurhash), [this issue](https://github.com/woltapp/react-blurhash/issues/8) makes me think it isn't compatible with react native yet

**Comment by mrousavy** [comment]
@ODINA101 @m5r I have created a lightweight and fast react native component for the blurhash library which includes asynchronous decoding and even an encoder. Check it out at [mrousavy/react-native-blurhash](https://github.com/mrousavy/react-native-blurhash)
