### ISSUE TITLE
Removed from registry?

### ISSUE THREAD

**Issue by frkmarko** [m5r/gatsby-transformer-blurhash#4]
The registry is currently returning 404 not found for this plugin. Any ideas?

```
+ npm ci
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@m5r/gatsby-transformer-blurhash/-/gatsby-transformer-blurhash-1.0.1.tgz
npm ERR! 404 
npm ERR! 404 '@m5r/gatsby-transformer-blurhash@1.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by m5r** [comment]
I've reproduced the bug and I'm getting in touch with npm support to further investigate

**Comment by preetjdp** [comment]
Hey, @frkmarko doing this worked.
```
npm install m5r/gatsby-transformer-blurhash#master
```

PS if it does not work, try removing the `package-lock.json`

**Comment by frkmarko** [comment]
Thanks @preetjdp but I am really looking to get this to back to working again with my pipeline using `npm ci`.

**Comment by m5r** [comment]
I just got an answer from npm support and the package should be accessible once again, I'm closing the issue
